server:
  servlet:
    context-path: /

logging:
  level:
    web: INFO
  config: classpath:log4j.xml


spring:
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
    show-sql: true
    format-sql: true
  datasource:
    url: jdbc:h2:file:data/app.db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
      platform: h2

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

jwt:
  secret-key: IslamIsMyLife1!
  validity: 600_000
  prefix: Bearer
  header: Authorization
  issuer: Accenture